INSERT INTO `film` (`idfilm`, `titolo`, `regista`, `genere`, `durata`, `nazione`, `anno`, `descrizione`, `trailer`, `lingua`, `attori`, `attivo` ) VALUES
( NULL, 'Killers of the Flower Moon', 'Martin Scorsese', 'Drammatico', 205, 'USA', 2023, 'Oklahoma, primi anni Venti. Ernest Burkhart ha combattuto in guerra e torna nella nativa Fairfax in cerca di fortuna.', 'https://youtu.be/7cx9nCHsemc?si=FqLtGfXZT5f4-YYA','Ita','Leonardo Di Caprio, Robert De Niro, Jesse Plemons', 1),
( NULL, 'Hunger Games: la ballata dell''usignolo e del serpente', 'Francis Lawrence', 'Azione, Avventura', 165, 'USA', 2023, 'Anni prima di diventare il tirannico presidente di Panem, il diciottenne Coriolanus Snow è l ultima speranza per il buon nome della sua casata in declino: un orgogliosa famiglia caduta in disgrazia nel dopoguerra di Capitol City.','https://www.youtube.com/embed/kqAyrCadrQU?fs=1&autoplay=1','Ita','Rachel Zegler, Tom Blyth, Hunter Schafer', 1),
( NULL, 'Gremlins', 'Joe Dante', 'Fantastico', 111, 'USA', 1984, 'Rand Peltzer, inventore, ha trovato un regalo natalizio perfetto per suo figlio Bill: un piccolo mogwai tenero e buffo. ','https://www.youtube.com/embed/rKpl61np8aE?fs=1&autoplay=1','Ita','Phoebe Cates, Keye Luke, Zach Galligan', 1),
( NULL, 'The Marvels', 'Nia DaCosta', 'Azione', 101, 'USA', 2023, 'Carol Danvers alias Captain Marvel ha recuperato la propria identità dai tirannici Kree e si è vendicata della Suprema Intelligenza. Ma a causa di conseguenze impreviste, Carol deve farsi carico del peso di un universo destabilizzato.','https://www.youtube.com/embed/nrMX5IcQZpE?fs=1&autoplay=1','Ita','Brie Larson, Teyonah Parris, Zawe Ashton', 1),
( NULL, 'The Nun II', 'Michael Chaves', 'Horror', 109, 'USA', 2023, '1956 - Francia. Un prete viene assassinato. Un male si sta diffondendo. Il sequel del film campione d''incassi segue le vicende di Suor Irene, quando viene a trovarsi nuovamente faccia a faccia con Valak, la suora demoniaca.','https://youtu.be/QF-oyCwaArU','Ita','Bonnie Aarons, Taissa Farmiga, Anna Popplewell', 1),
( NULL, 'Oppenheimer', 'Christopher Nolan', 'Biografico, Drammatico, Storico', 180, 'USA', 2023, 'Basato sulla biografia Robert Oppenheimer, il padre della bomba atomica di Kai Bird e Martin J. Sherwin, il film racconta la vita del fisico teorico statunitense J. Robert Oppenheimer.','https://youtu.be/bK6ldnjE3Y0','Ita','Cillian Murphy, Emily Blunt, Robert Downey Jr., Matt Damon, Rami Malek', 0),
( NULL, 'Povere Creature!', 'Yorgos Lanthimos', 'Fantascienza', 101, 'USA', 2023, 'Oltre alle cicatrici che lo sfigurano e alle terribili menomazioni del suo fisico, Godwin Baxter deve a suo padre anche una sincera passione per il metodo scientifico e le pratiche chirurgiche.','https://youtu.be/RlbR5N6veqw','Ita','Emma Stone, Margaret Qualley, Willem Dafoe, Mark Ruffalo', 0);
ALTER TABLE `film`
  MODIFY `idfilm` int(11) NOT NULL AUTO_INCREMENT;
  