INSERT INTO `film` (`idfilm`, `titolo`, `regista`, `genere`, `durata`, `nazione`, `anno`, `descrizione`, `trailer`, `locandina`, `lingua`, `attori`, `stato` ) VALUES
( NULL, 'Garfield: Una Missione Gustosa', 'Mark Dindal', 'animazione', NULL, NULL, '2024', 'In questa nuova avventura, dopo un inaspettato incontro con il padre perduto da tempo, il trasandato gatto di strada Vic, Garfield e il suo amico canino Odie sono costretti a lasciare la loro vita piena di comodità per unirsi a Vic in una rapina ad alto rischio.', 'https://youtu.be/FiTUp0SU1f0?si=ZBhh0CJk_p9_V0WZ', 'Garfield.png', NULL, NULL, 2),
( NULL, 'Mean Girls', 'Arturo Perez Jr. and Samantha Jayne', 'commedia, musicale', NULL, NULL, '2024', 'Cady Heron riesce a integrarsi nel suo nuovo liceo ed entra a far parte della cricca di ragazze di prima qualità, le Plastics. Poi, però, commette il tragico errore di innamorarsi di Aaron Samuels, ex fidanzato di Regina George.', 'https://youtu.be/fFtdbEgnUOk?si=L6MItsJwSYWo6ZxJ', 'mean-girls.png', NULL, NULL, 2),
( NULL, 'Argylle', 'Matthew Vaughn' ,'spionaggio, azione', NULL, NULL, '2024', 'Elly Conway, una solitaria scrittrice di best-seller di spionaggio, gradisce passare le serate davanti al computer in compagnia del suo gatto Alfie. Si ritroverà catapultata nel vero mondo dello spionaggio quando le trame dei suoi libri, incentrati su Argylle, un agente segreto, inizieranno a diventare reali. Le vicende raccontate nei suoi romanzi sembreranno essere troppo simili alle attività svolte da una organizzazione segreta di spionaggio. Quando la spia Aiden le si presenta per salvarla da un rapimento, Elly e Alfie si ritroveranno in un mondo dove nulla è come sembra.', 'https://youtu.be/7mgu9mNZ8Hk?si=qBKDZ0Jbrle9wYeL', 'Argylle.png', NULL, NULL, 2),
( NULL, 'Arthur the King', 'Simon Cellan Jones', 'drama, azione', NULL, NULL, '2024', 'Un campione di raid - le cui gare prevedono un viaggio avventuroso con destinazione prefissata che comporta la percorrenza di una lunga distanza - adotta un cane randagio di nome Arthur, che si unisce a lui in una gara di resistenza.', 'https://youtu.be/wjDJNEPghNY?si=rNm9ubF8iudZ1W4B', 'arthur-the-king.png', NULL, NULL, 2),
( NULL, 'Joker: Folie à Deux', 'Todd Phillips', 'thriller psicologico musicale',NULL, NULL, '2024', 'Sequel di Joker; un musical ambientato principalmente all’Arkham Asylum e si concentrerà sul tempo trascorso da Joker nell’iconico manicomio criminale.', 'https://youtu.be/03ymBj144ng?si=64Qni2C8o1RFj_zF', 'joker-2.png', NULL, NULL, 2),
( NULL, 'Beetlejuice 2', 'Tim Burton', 'thriller, fantasy',NULL, NULL, '2024', NULL, 'https://youtu.be/llnuyh1wo8A?si=4c_ibI70GMIMhlRK', 'beetlejuice-2.png', NULL, NULL, 2);
ALTER TABLE `film`
  MODIFY `idfilm` int(11) NOT NULL AUTO_INCREMENT;
